agenda/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("sala.urls")),
    path("reserva/", include("reserva.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("registration.urls")),
    path("admin/", admin.site.urls),
]

reserva/urls.py
from django.urls import path, include

from . import views


urlpatterns = [
    path("addreserva/", views.add_reserva, name="add_reserva"),
    path("listarreservas/", views.listar_reservas, name="listar_reservas"),
    path("<int:id>/", views.add_reserva, name="reserva_update"),
    path("delete_reserva_all/", views.delete_reserva_all, name="delete_reserva_all"),
    path ('editar_reserva/<int:id>/',views.editar_reserva,name='editar_reserva'),

    
]

sala/urls.py
from django.urls import path, include

# from rest_framework import routers

from . import views


urlpatterns = [
    path("home/", views.home, name="home"),
    path("addsala/", views.add_sala, name="add_sala"),
    path("listarsalas/", views.listar_salas, name="listar_salas"),
    path("delete_sala_all/", views.delete_salas_all, name="delete_sala_all"),
    path ('editar_sala/<int:id>/',views.editar_sala,name='editar_sala'),

]

reserva/models.py
from datetime import date, timezone
from statistics import mode
import django
from django.db import models

# Create your models here.
class Reserva(models.Model):
    titulo = models.CharField(max_length=50)
    tiempo_inicio = models.DateTimeField(
        auto_now=False,
        auto_now_add=False,
        blank=True,
        default=django.utils.timezone.now,
    )
    tiempo_fin = models.DateTimeField(
        auto_now=False,
        auto_now_add=False,
        blank=True,
        default=django.utils.timezone.now,
    )
    username = models.ForeignKey(
        "auth.user", on_delete=models.CASCADE, blank=True, null=True
    )
    descripcion = models.CharField(max_length=500, blank=True)
    sala_id = models.ForeignKey(
        "sala.sala", on_delete=models.CASCADE, blank=True, null=True, default=1
    )
    invitados = models.CharField(max_length=254, null=True,blank=True)
    recordatorio = models.BooleanField(default=True)

    def add(self):
        self.save

    def __str__(self):
        return self.name

reserva/forms.py
from cProfile import label
from pyexpat import model
from django.db.models import fields
from django import forms
from .models import Reserva


class ReservaForm(forms.ModelForm):
    descripcion = forms.CharField(
        widget=forms.Textarea(attrs={"rows": "3", "cols": "5"})
    )

    class Meta:
        model = Reserva
        fields = [
            "tiempo_inicio",
            "tiempo_fin",
            "username",
            "descripcion",
            "sala_id",
            "titulo",
            "invitados",
            "recordatorio",
        ]

        labels = {
            "tiempo_inicio": "Inicio",
            "tiempo_fin": "Fin",
            "username": "usuario",
            "descripcion": "Descripción",
            "sala_id": "Sala",
            "recordatorio":"Recordatorio"
        }

reserva/views.py
from collections import UserList
from datetime import datetime
from smtplib import SMTPAuthenticationError
import threading
from django.shortcuts import redirect, render
from reserva.forms import ReservaForm
import threading
from django.contrib.auth.decorators import login_required

from reserva.models import Reserva
from sala.models import Sala
import sweetify
import pytz
from django.utils.dateparse import parse_date
from django.contrib.auth.models import User
from django.core.mail import send_mail
from agenda.settings import EMAIL_HOST, EMAIL_HOST_PASSWORD, EMAIL_HOST_USER, EMAIL_PORT
from django.core.mail import EmailMessage
from django.core.paginator import Paginator
from django.contrib import messages
import logging

logger = logging.getLogger("agenda")


# Create your views here.
Connected = False


@login_required
def add_reserva(request, id=0):
    if request.method == "GET":
        if id == 0:
            form = ReservaForm()
        else:
            reserva = Reserva.objects.get(pk=id)

            form = ReservaForm(instance=reserva)
        return render(request, "reserva/add_reserva.html", {"form": form})
    else:
        if id == 0:
            form = ReservaForm(request.POST)
        else:
            reserva = Reserva.objects.get(pk=id)
            form = ReservaForm(request.POST, instance=reserva)
            iniciohora = request.POST.get("tiempo_inicio")

        if form.is_valid():
            salaid = request.POST.get("sala_id")
            iniciohora = request.POST.get("tiempo_inicio")
            dateiniciohora = datetime.strptime(iniciohora, "%d/%m/%Y %H:%M:%S")
            finhora = request.POST.get("tiempo_fin")
            datefinhora = datetime.strptime(finhora, "%d/%m/%Y %H:%M:%S")
            estadosala = verificar_estado(salaid, dateiniciohora, datefinhora)
            invitados = request.POST.get("invitados")
            descripcion = request.POST.get("descripcion")
            if estadosala == False:
                sweetify.error(request, "Sala ocupada", persistent=":(")
            else:
                reserva = form.save(commit=False)
                reserva.username = request.user
                reserva.save()
                print(invitados)
                result_env = send_email(
                    invitados,
                    descripcion,
                    salaid,
                    iniciohora,
                    finhora,
                    asunto="Reserva Realizada",
                )
                if result_env == None:
                    sweetify.error(
                        request,
                        "Error en el envio de mail, se realizo la reserva igualmente",
                        persistent=":(",
                    )

                else:
                    sweetify.success(
                        request,
                        "Exito",
                        text="Apagado Correctamente",
                        persistent="Aceptar",
                    )

        return redirect("/home/")


def send_email(invitados, descripcion, salaid, iniciohora, finhora, asunto):
    sender_email = "web@vic.uy"
    recipient_list = invitados.split(";")

    email = EmailMessage(
        subject=asunto,
        body=f"Se realizo una reserva de la sala "
        + salaid
        + "para el evento "
        + descripcion
        + " a la hora de inico "
        + iniciohora
        + " y finalizacion "
        + finhora,
        from_email=sender_email,
        to=recipient_list,
    )
    try:
        logger.debug("Entre al try para enviar el email")

        email.send()
        return True

    except SMTPAuthenticationError as auth_error:
        logger.error(f"Error de autenticación SMTP: {str(auth_error)}")
        return None

    except Exception as e:
        logger.error(f"Otro error: {str(e)}")
        return None

    finally:
        email.get_connection().close()


def verificar_estado(salaid, dateiniciohora, datefinhora):
    utc = pytz.UTC
    reservas = Reserva.objects.filter(
        tiempo_fin__range=[dateiniciohora, datefinhora], sala_id_id=salaid
    )
    if not reservas:
        return True
    else:
        return False


@login_required
def listar_reservas(request):
    reservas = Reserva.objects.select_related("sala_id", "username").order_by(
        "tiempo_inicio"
    )

    paginator = Paginator(reservas, 10)
    page_number = request.GET.get("page")
    page_object = paginator.get_page(page_number)

    context = {
        "page_object": page_object,
    }

    return render(request, "reserva/edit_reserva.html", context)


@login_required
def delete_reserva_all(request):
    if request.method == "POST":
        ids_reserva_delete = request.POST.getlist("ids_reserva_delete")
        ids_reserva_delete = list(map(int, ids_reserva_delete))

        reservas = Reserva.objects.filter(id__in=ids_reserva_delete)
        if ids_reserva_delete != []:
            for reserva in reservas:
                dateiniciohora = datetime.strftime(
                    reserva.tiempo_inicio, "%d/%m/%Y %H:%M:%S"
                )
                datefinhora = datetime.strftime(reserva.tiempo_fin, "%d/%m/%Y %H:%M:%S")

                cancelacion = send_email(
                    invitados=reserva.invitados,
                    descripcion=reserva.descripcion,
                    salaid=reserva.sala_id.nombre,
                    iniciohora=dateiniciohora,
                    finhora=datefinhora,
                    asunto="Reserva Cancelada",
                )
                print(cancelacion)
                if cancelacion == True:
                    reserva.delete()
                    sweetify.success(
                        request,
                        "Exito",
                        text="Eliminado Correctamente",
                        persistent="Aceptar",
                    )
                else:
                    sweetify.error(
                        request,
                        "Error",
                        text="No se pudo enviar el correo de cancelación, pero igualmente se elimina del sistema",
                        persistent="Aceptar",
                    )
                    reserva.delete()

            return redirect("listar_reservas")

        else:
            sweetify.error(
                request,
                "Error",
                text="Debe seleccionar al menos una sala",
                persistent="Aceptar",
            )
            return redirect("listar_reservas")

    else:
        reservas = Reserva.objects.all()
        return redirect("listar_reservas", {"reservas": reservas})


@login_required
def editar_reserva(request, id):
    reserva = Reserva.objects.get(pk=id)
    if request.method == "GET":
        form = ReservaForm(instance=reserva)
        return render(request, "reserva/add_reserva.html", {"form": form})
    else:
        form = ReservaForm(request.POST, instance=reserva)
        if form.is_valid():
            dateiniciohora = datetime.strftime(reserva.tiempo_inicio, "%d/%m/%Y %H:%M:%S")
            datefinhora = datetime.strftime(reserva.tiempo_fin, "%d/%m/%Y %H:%M:%S")

            modificacion = send_email(
                    invitados=reserva.invitados,
                    descripcion=reserva.descripcion,
                    salaid=reserva.sala_id.nombre,
                    iniciohora=dateiniciohora,
                    finhora=datefinhora,
                    asunto="Reserva Modificada",
                )
            if modificacion == True:
                reserva.save()
           
                sweetify.success(request, "Exito", text="Editado Correctamente", persistent="Aceptar")
            else:
                sweetify.error(request, "Error", text="No se pudo enviar el correo de modificación", persistent="Aceptar")
                reserva.save()
        
        else:
            sweetify.error(request, "Error", text="No se pudo editar", persistent="Aceptar")
        return redirect("/home/")


# def envio_recordatorio(id_reserva):
#     subtwo = threading.Thread(target=envio_recordatorio)
#     subtwo.start()

reserva/templates/reserva/add_reserva.html
{% extends 'sala/base.html' %}
{% load bootstrap5 %}

{% load crispy_forms_tags %}
{{form.mobile|as_crispy_field}}

{% load static %}
{% block content %}

{% block extra_datetime %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
{% endblock extra_datetime %}

    <div class="container ">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 col-12">
                <form class="reserva shadow" method="POST" style="background-color: white; padding:20px">
                    {% csrf_token %} 
                    <div class="row g-3">
                        <div class="col">
                            {{ form.tiempo_inicio|as_crispy_field }}

                        </div>
                        <div class="col">
                            {{ form.tiempo_fin|as_crispy_field }}

                        </div>
                    </div>
                   
                    <div class="row g-3">
                        <div class="col-sm">
                            {{ form.titulo|as_crispy_field }}

                        </div>
                        
            
                    </div>
                  
                    <div class="row">
                        <div class="col">
                            {{ form.descripcion|as_crispy_field }}

                        </div>
            
                    </div>
            
                    <div class="row">
                        <div class="col-sm">
                            {{ form.invitados|as_crispy_field }}

                        </div>
                        
                           
                    </div>
                    <div class="row">
                        <div class="col">
                            {{ form.sala_id|as_crispy_field }}

                        </div>
                        <div class="col">
                            {{ form.recordatorio|as_crispy_field }}

                        </div>

                    </div>
                    <div class="text-center">
                    <button type="submit" class="btn btn-primary btn-user btn-block">Reservar</button>
                </div>
                
                    
                </form>

            </div>
            <div class="col-md-3"></div>

        </div>
    </div>

    


    {% block extra_js %}
    <script>
        jQuery.datetimepicker.setLocale('es');

        jQuery('#id_tiempo_inicio').datetimepicker({

            format:'d/m/Y H:i:s',
            inline:false,
            lang:'es'


        });
        jQuery('#id_tiempo_fin').datetimepicker({

            format:'d/m/Y H:i:s',
            inline:false,
            lang:'es'
        });

      </script>
    {% endblock extra_js %}





{% endblock content %}

reserva/templates/reserva/edit_reserva.html
{% extends 'sala/base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block content %}

<form action="{% url 'delete_reserva_all' %}" method="post">
    {% csrf_token %}

    <table class="table table-striped">
        <thead class="border-bottom font-weight-bold">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="seleccionar-todo">
                <label class="form-check-label" for="seleccionar-todo">
                    Seleccionar todo
                </label>
            </div>
            <tr>
              <td>id</td>
              <td>Inicio</td>
              <td>Fin</td>
              <td>Sala</td>
              <td></td>

            </tr>
        </thead>
        <tbody>
            {% for r in page_object  %}
                <tr>
                    <td><input type="checkbox" name="ids_reserva_delete" value="{{ r.id }}">{{r.id}}</td>
                    <td>{{r.tiempo_inicio}}</td>
                    <td>{{r.tiempo_fin}}</td>
                    <td>{{r.sala_id.nombre}}</td>
                    <td>
                        <a href="{% url 'editar_reserva' r.id %}" class="btn text-secondary px-0">
                            <img src="{% static 'icons/edit.svg' %}" alt="">
                        </a>
                        <form action="{% url 'delete_reserva_all'  %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <input type="hidden" name="id_reserva_individual" value="{{ r.id }}">
                            <button type="submit" class="btn-notstyle">
                                <img src="{% static 'icons/trash-2.svg' %}" alt="">
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <button type="submit" class="btn btn-danger float-right" onclick="return confirm('¿Estás seguro de que deseas eliminar todas las reservas seleccionadas?')">
        <img src="{% static 'icons/trash-all.svg' %}" alt="">
    </button>

</form>

<nav>
</nav>

{% block scripts %}
<script>
    const selectAllCheckbox = document.getElementById('seleccionar-todo');
    const checkboxes = document.getElementsByName('ids_reserva_delete');

    selectAllCheckbox.addEventListener('change', (event) => {
        checkboxes.forEach((checkbox) => {
            checkbox.checked = event.target.checked;
        });
    });
</script>
{% endblock %}

{% endblock content %}